### ISSUE TITLE
I have some problems in conv_fusion.py

### ISSUE THREAD

**Issue by Kaptainz1** [tomar840/two-stream-average-fusion-for-action-recognition-in-videos#12]
When I run conv_fusion.py it has problems:
==> (Training video, Validation video):( 11 0 )
Eligible videos for training : 10 videos
Eligible videos for validation: 0 videos
Epoch 0/19
----------
Traceback (most recent call last):
  File "conv_fusion.py", line 349, in <module>
    model = train_model(model, criterion, optimizer,scheduler, num_epochs=20)
  File "conv_fusion.py", line 167, in train_model
    outputs = model(spat_data, temp_data)
  File "/home/el304/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "conv_fusion.py", line 266, in forward
    y[:,(2*i),:,:]  = x1[:,i,:,:] 

**IndexError: too many indices for tensor of dimension 2**

Can someone help me?

**Comment by kevio33** [comment]
hi, i got the same probliem,did you solve it?
