### ISSUE TITLE
How to inference after training the model?

### ISSUE THREAD

**Issue by timthegod** [tomar840/two-stream-average-fusion-for-action-recognition-in-videos#6]
I fixed some bug and start training.
How can I test it?
And how to train our own model using own data?
Thank you!

**Comment by shijubushiju** [comment]
I have the same problem,how did solve it?

**Comment by ChiehYung** [comment]
Can you share the environment with me!
I face some bug that i can't start training!

D:\Project_venv\two-stream-fusion-for-action-recognition-in-videos-master\lib\site-packages\torch\optim\lr_scheduler.py:82: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "conv_fusion.py", line 347, in <module>
    model = train_model(model, criterion, optimizer,scheduler, num_epochs=20)
  File "conv_fusion.py", line 150, in train_model
    for data in fullloader[phase]:
  File "D:\Project_venv\two-stream-fusion-for-action-recognition-in-videos-master\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Project_venv\two-stream-fusion-for-action-recognition-in-videos-master\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "D:\Program Files\python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\Program Files\python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Program Files\python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Program Files\python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Program Files\python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle dict_keys objects

thanks!!

**Comment by Morning-YU** [comment]
Hi, timthegod! 

I met this problem, 

The videoname variable is not defined. 
https://github.com/tomar840/two-stream-fusion-for-action-recognition-in-videos/blob/master/dataloader/split_train_test_video.py#L50

Could tell me how to slove?
